name: Deploy
on:
  workflow_dispatch:
jobs:
    transfer:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.4'

        - name: Build
          run: go build -v -buildmode=c-shared -o output.so ./...

        - name: Copy file to server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSHKEY }}
            source: "output.so"
            target: "/path/to/target/directory"