name: Deploy
on:
  workflow_dispatch:
jobs:
    transfer:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.24.3'

        - name: Build
          run: |
            go install github.com/a-h/templ/cmd/templ@latest
            export CGO_ENABLED=0
            templ generate
            go build -v -o main.so ./cmd/main.go

        - name: Copy file to server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            source: "main.so"
            target: "~/"

        - name: Restart the site
          run: curl -X POST --basic --user "${{secrets.WEBAPIKEY}} account=${{secrets.WEBACCOUNT}}:" https://api.alwaysdata.com/v1/site/${{secrets.SITENUMBER}}/restart/
